const express = require("express");
const router = express.Router();
const itemController = require("../controllers/item");
const reviewController = require("../controllers/review");
const tagController = require("../controllers/tag");
const parser = require("../middleware/cloudinary");
router.get("/", itemController.getItems);
router.get("/:id", itemController.getItem);
router.post("/", parser.array("imageUrls"), itemController.addItem);
router.post("/addReview/:id", reviewController.addReview);
module.exports = router;
